version: "3.3"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
        ports:
            - 3000:8000
            - 35729:35729
